"""make puzzle definition optional

Revision ID: 38bf25514574
Revises: f89b876c0158
Create Date: 2026-09-28 18:44:03.365948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bf25514574'
down_revision = 'f89b876c0158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.alter_column('definition',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
