"""create core tables

Revision ID: f89b876c0158
Revises: 
Create Date: 2026-09-28 17:52:50.179479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89b876c0158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('last_streak_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('clue', sa.Text(), nullable=False),
    sa.Column('definition', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=64), nullable=False),
    sa.Column('enumeration', sa.String(length=32), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('technique', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'practice' AND publish_date IS NULL) OR (kind = 'daily' AND (status = 'draft' OR publish_date IS NOT NULL))", name=op.f('ck_puzzles_publish_date_matches_kind')),
    sa.CheckConstraint("kind IN ('daily', 'practice')", name=op.f('ck_puzzles_kind_valid')),
    sa.CheckConstraint("status IN ('draft', 'ready')", name=op.f('ck_puzzles_status_valid')),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name=op.f('ck_puzzles_difficulty_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzles')),
    sa.UniqueConstraint('publish_date', name=op.f('uq_puzzles_publish_date'))
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_events_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_events_puzzle_id_puzzles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_events_puzzle_id_type', ['puzzle_id', 'type'], unique=False)

    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('guess_count', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('letters_revealed', sa.Integer(), nullable=False),
    sa.Column('counts_for_streak', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'solved', 'revealed')", name=op.f('ck_plays_status_valid')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_plays_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_plays_puzzle_id_puzzles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plays')),
    sa.UniqueConstraint('player_id', 'puzzle_id', name=op.f('uq_plays_player_id'))
    )
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plays_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_puzzle_id'), ['puzzle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plays_puzzle_id'))
        batch_op.drop_index(batch_op.f('ix_plays_player_id'))

    op.drop_table('plays')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_puzzle_id_type')
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    op.drop_table('puzzles')
    op.drop_table('players')
    # ### end Alembic commands ###
